### ISSUE TITLE
help! whp couldn't start error

### ISSUE THREAD

**Issue by Brahmashirsha** [smoochiee/Ble-jammer#1]
tried in both vspi nd hspi mod facing same issue

configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
E (7) wHP couldn't start !!!

**Comment by smoochiee** [comment]
make sure your wiring is correct and stable..as nrf is sensitive
