### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Tecnologiko** [smoochiee/Ble-jammer#3]
I followed all the steps in the guide in detail but it fails to interrupt or disturb the connection between my smartphone and my Bluetooth speaker. Help 

Telegram: @Tecn0logik0

![Uploading 17248372081012457762007368009411.jpg…]()

**Comment by smoochiee** [comment]
you pm me ryt?> I followed all the steps in the guide in detail but it fails to interrupt or disturb the connection between my smartphone and my Bluetooth speaker. Help 
> 
> Telegram: @Tecn0logik0
> 
> ![Uploading 17248372081012457762007368009411.jpg…]()
>

**Comment by smoochiee** [comment]
you pm me ryt?
